baseURL = "https://blog.webartisan.pw/"
defaultContentLanguage = "es"
title = "WEBartisan"
theme = "terminal"

# Your Google analytics code.
googleAnalytics = "UA-41662036-4"
# Your Disqus sortname.
disqusShortname = "WebArtisanPW"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 5

[params]
    # dir name of your blog content (default is `content/posts`)
    contentTypeName = "posts"

    # ["orange", "blue", "red", "green", "pink"]
    themeColor = "orange"

    # if you set this to 0, only submenu trigger will be visible
    showMenuItems = 2

    # show selector to switch language
    showLanguageSelector = false

    # set theme to full screen width
    fullWidthTheme = false

    # center theme with default width
    centerTheme = true

    # set a custom favicon (default is a `themeColor` square)
    # favicon = "favicon.ico"

    # set all headings to their default size (depending on browser settings)
    # it's set to `true` by default
    # oneHeadingSize = false

[languages]
  [languages.es]
    languageName = "Español"
    title = "WEBartisan"
    subtitle = "Building the web!!!"
    keywords = "tech blog, blog de tecnologia, webartisan, web artisan"
    copyright = ""
    menuMore = "Mostrar más"
    readMore = "Leer más"
    readOtherPosts = "Leer otros posts"

    [languages.es.params.logo]
      logoText = "WEBartisan"
      logoHomeLink = "/"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.es.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.es.menu.main]]
        identifier = "faq"
        name = "FAQ"
        url = "/faq"

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/tonirilix/webartisan-yt-channel"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/WebArtisanPW"

# Enable tags.
[taxonomies]
   tag = "tags"